# Generated by Django 2.0.4 on 2018-06-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_tour_reserves'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reserves',
            field=models.ManyToManyField(blank=True, related_name='user_reserves', to='tours.Tour'),
        ),
    ]
