# Generated by Django 2.0.4 on 2018-06-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('begin_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('places', models.ManyToManyField(blank=True, related_name='tour_places', to='tours.Place')),
                ('reserves', models.ManyToManyField(blank=True, related_name='tour_reserves', to='profiles.Profile')),
            ],
        ),
    ]
