# Generated by Django 2.0.4 on 2018-06-11 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='reserves',
        ),
    ]
