# Generated by Django 2.0.4 on 2018-06-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_tour_reserves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='value',
            new_name='value_adult',
        ),
        migrations.AddField(
            model_name='tour',
            name='value_children',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
